routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Auth::routes(['verify' => true]);

Route::group(['middleware' => 'auth'], function() {
    
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::resource('/whisper',App\Http\Controllers\WhisperController::class)->only(['index', 'create', 'store', 'show', 'edit', 'update', 'destroy']);
    Route::resource('users',App\Http\Controllers\UserController::class)->only(['index', 'show', 'edit', 'update']);
    Route::get('users/{user}/delete', [App\Http\Controllers\UserController::class, 'delete'])->name('delete');
    Route::post('users/{user}/follow', [App\Http\Controllers\UserController::class, 'follow'])->name('follow');
    Route::delete('users/{user}/unfollow', [App\Http\Controllers\UserController::class, 'unfollow'])->name('unfollow');
    Route::get('users/{user}/following', [App\Http\Controllers\UserController::class, 'following'])->name('following');
    Route::get('users/{user}/follower', [App\Http\Controllers\UserController::class, 'follower'])->name('follower');
    Route::resource('comments', App\Http\Controllers\CommentsController::class)->only(['store','edit','update','destroy']);  
    Route::get('/search', [App\Http\Controllers\SearchController::class, 'index']);
    Route::resource('favorites', App\Http\Controllers\FavoritesController::class)->only(['destroy', 'store']);

});

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\softDeletes;

class Comment extends Model
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'text'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getComments(Int $whisper_id)
    {
        return $this->with('user')->where('whisper_id', $whisper_id)->get();
    }

    public function commentStore(Int $user_id, Array $data)
    {
        $this->user_id = $user_id;
        $this->whisper_id = $data['whisper_id'];
        $this->text = $data['text'];
        $this->save();

        return;
    }
    public function getEditComment(Int $user_id, Int $comment_id)
    {
        return $this->where('user_id', $user_id)->where('id', $comment_id)->first();
    }


    public function commentUpdate(Int $comment_id, Array $data)
    {
        $this->id = $comment_id;
        $this->text = $data['text'];
        $this->update();

        return;
    }

    public function commentDestroy(Int $user_id, Int $comment_id)
    {
        return $this->where('user_id', $user_id)->where('id', $comment_id)->delete();
    }

}

app/Http/Controllers/CommentsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Models\Comment;
use App\Models\Follower;
use App\Models\Whisper;

class CommentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Comment $comment)
    {
        $user = auth()->user();
        $data = $request->all();
        $validator = Validator::make($data, [
            'whisper_id' =>['required', 'integer'],
            'text'     => ['required', 'string', 'max:140']
        ]);

        $validator->validate();
        $comment->commentStore($user->id, $data);

        return back();
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */


    public function edit(Comment $comment)
    {
        $user = auth()->user();
        $comments = $comment->getEditComment($user->id, $comment->id);

        if (!isset($comments)) {
            return redirect('comments');
        }

        return view('comments.edit', [
            'user'   => $user,
            'comments' => $comments
        ]);
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    
    public function update(Request $request, Comment $comment)
    {
        $data = $request->all();
        $validator = Validator::make($data, [
            'text' => ['required', 'string', 'max:140']
        ]);
        $validator->validate();
        $comment->commentUpdate($comment->id, $data);
        
        return redirect('whisper/'.$comment->whisper_id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Comment $comment)
    {
        $user = auth()->user();
        $comment->commentDestroy($user->id, $comment->id);

        return back();
    }

}

resources/views/comments/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center col-12 px-5">
        <div class="col-md-12">
            <div class="card">
                <h2 class="card-header text-center"
                    >Edit post
                </h2>
                <div class="card-body">
                    <form method="POST" action="{{ route('comments.update', ['comment' => $comments]) }}">
                        @csrf
                        @method('PUT')

                        <div class="form-group row mb-0">
                            <div class="col-md-12 p-3 w-100 d-flex">
                                <img src="{{ asset('storage/profile_image/' .$user->profile_image) }}" class="rounded-circle" width="50" height="50">
                                <div class="ml-2 d-flex flex-column">
                                    <p class="mb-0">{{ $user->name }}</p>
                                    <a href="{{ url('users/' .$user->id) }}" class="text-secondary"><i>@</i>{{ $user->user_name }}</a>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <textarea class="form-control @error('text') is-invalid @enderror" name="text" required autocomplete="text" rows="4">{{ old('text') ? : $comments->text }}</textarea>

                                @error('text')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="col-md-12 text-right">
                                <p class="mb-4 text-danger">Within 140 characters</p>
                                <button type="submit" class="btn btn-outline-primary" name="submit"　onClick="history.go(-1);">
                                    Repost
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection