routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Auth::routes(['verify' => true]);

Route::group(['middleware' => 'auth'], function() {
    
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::resource('/whisper',App\Http\Controllers\WhisperController::class)->only(['index', 'create', 'store', 'show', 'edit', 'update', 'destroy']);
    Route::resource('users',App\Http\Controllers\UserController::class)->only(['index', 'show', 'edit', 'update']);
    Route::get('users/{user}/delete', [App\Http\Controllers\UserController::class, 'delete'])->name('delete');
    Route::post('users/{user}/follow', [App\Http\Controllers\UserController::class, 'follow'])->name('follow');
    Route::delete('users/{user}/unfollow', [App\Http\Controllers\UserController::class, 'unfollow'])->name('unfollow');
    Route::get('users/{user}/following', [App\Http\Controllers\UserController::class, 'following'])->name('following');
    Route::get('users/{user}/follower', [App\Http\Controllers\UserController::class, 'follower'])->name('follower');
    Route::resource('comments', App\Http\Controllers\CommentsController::class)->only(['store','edit','update','destroy']);  
    Route::get('/search', [App\Http\Controllers\SearchController::class, 'index']);
    Route::resource('favorites', App\Http\Controllers\FavoritesController::class)->only(['destroy', 'store']);

});

app/Models/Whisper.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Whisper extends Model
{
    use SoftDeletes;

    protected $table = 'whispers';
    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'text'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function favorites()
    {
        return $this->hasMany(Favorite::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }


    public function image()
    {
        return $this->hasMany(Image::class);
    }


    public function getUserTimeLine(Int $user_id)
    {
        return $this->where('user_id', $user_id)->orderBy('created_at', 'DESC')->paginate(50);
    }

    public function getTimeLines(Int $user_id, Array $follow_ids)
    {
        $follow_ids[] = $user_id;
        return $this->whereIn('user_id', $follow_ids)->orderBy('created_at', 'DESC')->paginate(50);
    }

    public function getWhisperCount(Int $user_id)
    {
        return $this->where('user_id', $user_id)->count();
    }
    public function whisperStore(Int $user_id, Array $data)
    {
        $this->user_id = $user_id;
        $this->text = $data['text'];
        $this->save();

        return;
    }

    public function getEditWhisper(Int $user_id, Int $whisper_id)
    {
        return $this->where('user_id', $user_id)->where('id', $whisper_id)->first();
    }

    public function whisperUpdate(Int $whisper_id, Array $data)
    {
        $this->id = $whisper_id;
        $this->text = $data['text'];
        $this->update();

        return;
    }

    public function whisperDestroy(Int $user_id, Int $whisper_id)
    {
        return $this->where('user_id', $user_id)->where('id', $whisper_id)->delete();
    }

    public function getWhisper(Int $whisper_id)
    {
        return $this->with('user')->where('id', $whisper_id)->first();
    }
}

app/Http/Controllers/WhisperController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Models\Whisper;
use App\Models\Comment;
use App\Models\User;
use App\Models\Follower;
use App\Models\Image;

class WhisperController extends Controller
{
    //
    public function index(Whisper $whisper, Follower $follower, Image $image)
    {
        $user = auth()->user();
        $follow_ids = $follower->followingIds($user->id);


        $following_ids = $follow_ids->pluck('followed_id')->toArray();
        $images = Image::get();


        $timelines = $whisper->getTimelines($user->id, $following_ids);

      

        return view('whispers.index', [
            'user'      => $user,
            'timelines' => $timelines,
            'images'    => $images,
        ]);
    }
    
    public function create()
    {
        $user = auth()->user();

        return view('whispers.create', [
            'user' => $user
        ]);
    }

    public function store(Request $request, Whisper $whisper)
    {
        $user = auth()->user();

        $data = $request->all();
        

        $validator = Validator::make($data, [
            'text' => ['required', 'string', 'max:140'],
        ]);

        $validator->validate();
        $whisper->whisperStore($user->id, $data);

        if ($request->hasFile('image_file1')) {

        $image = new Image;
        $filename = $request->file('image_file1')->store('public/post_image'); // publicフォルダに保存
        $image->image_file = str_replace('public/post_image/','',$filename); // 保存するファイル名からpublicを除外
        $image->whisper_id=$whisper->id;
        $image->save();
        
        }

        if ($request->hasFile('image_file2')) {

            $image = new Image;
            $filename = $request->file('image_file2')->store('public/post_image'); // publicフォルダに保存
            $image->image_file = str_replace('public/post_image/','',$filename); // 保存するファイル名からpublicを除外
            $image->whisper_id=$whisper->id;
            $image->save();
            
        }
        
        if ($request->hasFile('image_file3')) {

            $image = new Image;
            $filename = $request->file('image_file3')->store('public/post_image'); // publicフォルダに保存
            $image->image_file = str_replace('public/post_image/','',$filename); // 保存するファイル名からpublicを除外
            $image->whisper_id=$whisper->id;
            $image->save();
            
        }


        return redirect('whisper');
    }

    public function edit(Whisper $whisper)
    {
        $user = auth()->user();
        $whispers = $whisper->getEditWhisper($user->id, $whisper->id);

        if (!isset($whispers)) {
            return redirect('whispers');
        }

        return view('whispers.edit', [
            'user'   => $user,
            'whispers' => $whispers
        ]);
    }

    public function update(Request $request, Whisper $whisper)
    {
        $data = $request->all();
        $validator = Validator::make($data, [
            'text' => ['required', 'string', 'max:140']
        ]);

        $validator->validate();
        $whisper->whisperUpdate($whisper->id, $data);
       

        return redirect('users/'.$whisper->user_id);
    }

    public function destroy(Whisper $whisper)
    {
        $user = auth()->user();
        $whisper->whisperDestroy($user->id, $whisper->id);

        return back();
    }

    public function show(Whisper $whisper, Comment $comment)
    {
        $user = auth()->user();
        $whisper = $whisper->getWhisper($whisper->id);
        $comments = $comment->getComments($whisper->id);

        return view('whispers.show', [
            'user'     => $user,
            'whisper' => $whisper,
            'comments' => $comments
        ]);
    }


}

resources/views/whispers/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center col-12 px-5">
        <div class="col-md-12">
            <div class="card">
                <h2 class="card-header text-center">
                    Create post
                </h2>
                <div class="card-body">
                    <form method="POST" action="{{ route('whisper.store') }}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group row mb-0">
                            <div class="col-md-12 p-3 w-100 d-flex">
                                <img src="{{ asset('storage/profile_image/' .$user->profile_image) }}" class="rounded-circle" width="50" height="50">
                                <div class="ml-2 d-flex flex-column">
                                    <p class="mb-0">{{ $user->name }}</p>
                                    <a href="{{ url('users/' .$user->id) }}" class="text-secondary">
                                        <i>@</i>{{ $user->user_name }}
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <textarea class="form-control @error('text') is-invalid @enderror" placeholder="" name="text" required autocomplete="text" rows="4">{{ old('text') }}</textarea>

                                @error('text')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-12 text-right">
                            <input class="" name="image_file1" type="file" value="{{ old('image_file1') }}"><br>
                            <input class="" name="image_file2" type="file" value="{{ old('image_file2') }}"><br>
                            <input class="" name="image_file3" type="file" value="{{ old('image_file3') }}"><br>
                                <i class="fas fa-camera fa-2x"></i>
                                <p class="mb-4 text-danger">Within 140 characters</p>
                                <button type="submit" class="btn btn-outline-primary">
                                    Post
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/whispers/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center col-12 px-5">
        <div class="col-md-12">
            <div class="card">
                <h2 class="card-header text-center">
                    Edit post
                </h2>
                <div class="card-body">
                    <form method="POST" action="{{ route('whisper.update', ['whisper' => $whispers]) }}">
                        @csrf
                        @method('PUT')
                        <div class="form-group row mb-0">
                            <div class="col-md-12 p-3 w-100 d-flex">
                                <img src="{{ asset('storage/profile_image/' .$user->profile_image) }}" class="rounded-circle" width="50" height="50">
                                <div class="ml-2 d-flex flex-column">
                                    <p class="mb-0">{{ $user->name }}</p>
                                    <a href="{{ url('users/' .$user->id) }}" class="text-secondary"><i>@</i>{{ $user->user_name }}</a>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <textarea class="form-control @error('text') is-invalid @enderror" name="text" required autocomplete="text" rows="4">{{ old('text') ? : $whispers->text }}</textarea>

                                @error('text')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="col-md-12 text-right">
                                <p class="mb-4 text-danger">Within 140 characters</p>
                                <button type="submit" class="btn btn-outline-primary">
                                    Repost
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/whispers/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center col-12 px-5">
        TIMELINE
        @if (!empty($timelines ?? ''))
            @foreach ($timelines ?? '' as $timeline)
                <div class="col-md-12 mb-3">
                    <div class="card">
                        <div class="card-haeder p-3 w-100 d-flex">
                            <img src="{{ asset('storage/profile_image/' .$timeline->user->profile_image) }}" class="rounded-circle" width="50" height="50">
                            <div class="ml-2 d-flex flex-column">
                            <a href="{{ url('users/' .$timeline->user->id) }}" class="text-secondary"><p class="mb-0">{{ $timeline->user->name }}</p>
                                <i>@</i>{{ $timeline->user->user_name }}</a>
                            </div>
                            <div class="d-flex justify-content-end flex-grow-1">
                                <p class="mb-0 text-secondary">{{ $timeline->created_at->format('Y-m-d H:i') }}</p>
                            </div>
                        </div>
                        <div class="card-body">
                            {!! nl2br(e($timeline->text)) !!}
                        </div>

                        <div class="row">
                            @foreach ($images as $image)

                            @if ($timeline->id == $image->whisper_id)
                            
                                <div class="col-md-4">
                                    <img src="{{ asset('storage/post_image/' .$image->image_file) }}" class="img-rounded m-3" width="200" height="200">
                                </div>
                            
                            @endif
                            @endforeach
                        </div>

                        <div class="card-footer py-1 d-flex justify-content-end bg-white">
                            @if ($timeline->user->id === Auth::user()->id)
                                <div class="dropdown mr-3 d-flex align-items-center">
                                    <form method="POST" action="{{ url('whisper/' .$timeline->id) }}" class="mb-0">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="dropdown-item del-btn"><i class="fas fa-trash-alt"></i></button>
                                    </form>
                                </div>
                            @endif
                            <div class="mr-3 d-flex align-items-center">
                                <a href="{{ url('whisper/' .$timeline->id) }}"><i class="far fa-comment fa-fw"></i></a>
                                <p class="mb-0 text-secondary">{{ count($timeline->comments) }}</p>
                            </div>
                            <div class="d-flex align-items-center">
                                @if (!in_array($user->id, array_column($timeline->favorites->toArray(), 'user_id'), TRUE))
                                    <form method="POST" action="{{ url('favorites/') }}" class="mb-0">
                                        @csrf

                                        <input type="hidden" name="whisper_id" value="{{ $timeline->id }}">
                                        <button type="submit" class="btn p-0 border-0 text-primary"><i class="far fa-heart fa-fw"></i></button>
                                    </form>
                                @else
                                    <form method="POST" action="{{ url('favorites/' .array_column($timeline->favorites->toArray(), 'id', 'user_id')[$user->id]) }}" class="mb-0">
                                        @csrf
                                        @method('DELETE')

                                        <button type="submit" class="btn p-0 border-0 text-danger"><i class="fas fa-heart fa-fw"></i></button>
                                    </form>
                                @endif
                                <p class="mb-0 text-secondary">{{ count($timeline->favorites) }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        @else
        Follow someone first
        @endif
    </div>
    <div class="my-4 d-flex justify-content-center">
        {{ $timelines ?? ''->links() }}
    </div>
@endsection

resources/views/whispers/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center col-12 px-5">
        <div class="col-md-12 mb-3">
            <div class="card">
                <div class="card-haeder p-3 w-100 d-flex">
                    <img src="{{ asset('storage/profile_image/' .$whisper->user->profile_image) }}" class="rounded-circle" width="50" height="50">
                    <div class="ml-2 d-flex flex-column">
                        <p class="mb-0">{{ $whisper->user->name }}</p>
                        <a href="{{ url('users/' .$whisper->user->id) }}" class="text-secondary"><i>@</i>{{ $whisper->user->user_name }}</a>
                    </div>
                    <div class="d-flex justify-content-end flex-grow-1">
                        <p class="mb-0 text-secondary">{{ $whisper->created_at->format('Y-m-d H:i') }}</p>
                    </div>
                </div>
                <div class="card-body">
                    {!! nl2br(e($whisper->text)) !!}
                </div>
                <div class="card-footer py-1 d-flex justify-content-end bg-white">
                    @if ($whisper->user->id === Auth::user()->id)
                        <div class="dropdown mr-3 d-flex align-items-center">
                            <a href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-ellipsis-v fa-fw"></i>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <form method="POST" action="{{ url('whisper/' .$whisper->id) }}" class="mb-0">
                                    @csrf
                                    @method('DELETE')

                                    <a href="{{ url('whisper/' .$whisper->id .'/edit') }}" class="dropdown-item">edit</a>
                                    <button type="submit" class="dropdown-item del-btn">delete</button>
                                </form>
                            </div>
                        </div>
                    @endif
                    <div class="mr-3 d-flex align-items-center">
                        <a href="{{ url('whispers/' .$whisper->id) }}"><i class="far fa-comment fa-fw"></i></a>
                        <p class="mb-0 text-secondary">{{ count($whisper->comments) }}</p>
                    </div>
                    <div class="d-flex align-items-center">
                        @if (!in_array(Auth::user()->id, array_column($whisper->favorites->toArray(), 'user_id'), TRUE))
                            <form method="POST" action="{{ url('favorites/') }}" class="mb-0">
                                @csrf

                                <input type="hidden" name="whisper_id" value="{{ $whisper->id }}">
                                <button type="submit" class="btn p-0 border-0 text-primary"><i class="far fa-heart fa-fw"></i></button>
                            </form>
                        @else
                            <form method="POST"action="{{ url('favorites/' .array_column($whisper->favorites->toArray(), 'id', 'user_id')[Auth::user()->id]) }}" class="mb-0">
                                @csrf
                                @method('DELETE')

                                <button type="submit" class="btn p-0 border-0 text-danger"><i class="fas fa-heart fa-fw"></i></button>
                            </form>
                        @endif
                        <p class="mb-0 text-secondary">{{ count($whisper->favorites) }}</p>
                    </div>
                </div>
            </div>
        </div>


        <div class="row justify-content-center col-12">
        <div class="col-md-10 mb-3">
            <ul class="list-group">
                @forelse ($comments as $comment)
                    <li class="list-group-item">
                        <div class="py-3 w-100 d-flex">
                            <img src="{{ asset('storage/profile_image/' .$comment->user->profile_image) }}" class="rounded-circle" width="50" height="50">
                            <div class="ml-2 d-flex flex-column">
                                <p class="mb-0">{{ $comment->user->name }}</p>
                                <a href="{{ url('users/' .$comment->user->id) }}" class="text-secondary"><i>@</i>{{ $comment->user->user_name }}</a>
                            </div>
                            <div class="d-flex justify-content-end flex-grow-1">
                                <p class="mb-0 text-secondary">{{ $comment->created_at->format('Y-m-d H:i') }}</p>
                            </div>
                        </div>
                        <div class="py-3 text-break">
                            {!! nl2br(e($comment->text)) !!}
                        </div>
                        <div class="card-footer py-1 d-flex justify-content-end bg-white">
                            @if ($comment->user->id === Auth::user()->id)
                                <div class="dropdown mr-3 d-flex align-items-center">
                                    <a href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fas fa-ellipsis-v fa-fw"></i>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                        <form method="POST" action="{{ url('comments/' .$comment->id) }}" class="mb-0">
                                            @csrf
                                            @method('DELETE')

                                            <a href="{{ url('comments/' .$comment->id .'/edit') }}" class="dropdown-item">edit</a>
                                            <button type="submit" class="dropdown-item del-btn">delete</button>
                                        </form>
                                    </div>
                                </div>
                            @endif
                        </div>
                    </li>
                @empty
                    <li class="list-group-item">
                        <p class="mb-0 text-secondary">No comments yet</p>
                    </li>
                @endforelse
                <li class="list-group-item">
                    <div class="py-3">
                        <form method="POST" action="{{ route('comments.store') }}">
                            @csrf

                            <div class="form-group row mb-0">
                                <div class="col-md-12 p-3 w-100 d-flex">
                                    <img src="{{ asset('storage/profile_image/' .$user->profile_image) }}" class="rounded-circle" width="50" height="50">
                                    <div class="ml-2 d-flex flex-column">
                                        <p class="mb-0">{{ $user->name }}</p>
                                        <a href="{{ url('users/' .$user->id) }}" class="text-secondary"><i>@</i>{{ $user->user_name }}</a>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <input type="hidden" name="whisper_id" value="{{ $whisper->id }}">
                                    <textarea class="form-control @error('text') is-invalid @enderror" name="text" required autocomplete="text" rows="4">{{ old('text') }}</textarea>

                                    @error('text')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-12 text-right">
                                    <p class="mb-4 text-danger">Within 140 characters</p>
                                    <button type="submit" class="btn btn-primary">
                                        Reply
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
@endsection